name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Get version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DMG_NAME=Smart Clipboard v$VERSION.dmg" >> $GITHUB_ENV

      - name: Package into .dmg
        run: |
          mkdir -p dist
          hdiutil create -volname "Smart Clipboard" \
            -srcfolder ./build \
            -ov -format UDZO \
            "dist/${{ env.DMG_NAME }}"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ env.VERSION }}
          name: v${{ env.VERSION }}
          generate_release_notes: true
          files: |
            dist/${{ env.DMG_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
